apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: admin-monitor
  namespace: prometheus
  labels:
    app: admin-monitor
spec:
  selector:
    matchLabels:
      app: admin-service
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: admin-port
      path: "/actuator/prometheus"
#
#---
#
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: admin-monitor-account
#  namespace: prometheus
#
#---
#
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: admin-monitor-bind
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: service-reader
#subjects:
#  - kind: ServiceAccount
#    name: admin-monitor-account
#    namespace: prometheus
#
#---
#
#
#apiVersion: monitoring.coreos.com/v1
#kind: Prometheus
#metadata:
#  name: admin-monitor-prometheus
#  namespace: prometheus
#spec:
#  serviceAccountName: admin-monitor-account
#  serviceMonitorSelector:
#    matchLabels:
#      app: admin-monitor
#  #  serviceMonitorNamespaceSelector:
#  #    matchLabels:
#  #      name: default
#  resources:
#    requests:
#      memory: 400Mi
#  enableAdminAPI: false