spring:
  cloud:
    kubernetes:
      enabled: false
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: c7998d45-774f-4de0-9aa5-0c7fb9e2a1e5
        enabled: true
        instance-enabled: true
      config:
        namespace: c7998d45-774f-4de0-9aa5-0c7fb9e2a1e5
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
      username: nacos
      password: nacos
  config:
    import:
      - optional:nacos:account.yml?refreshEnabled=true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/mall_user?allowMultiQueries=true&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: Abc@1234560
    driver-class-name: com.mysql.cj.jdbc.Driver
