apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: account-service-monitor
  namespace: prometheus
  labels:
    app: account
spec:
  selector:
    matchLabels:
      app: account
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: account-port
      path: "/actuator/prometheus"
      interval: 29s