server:
  port: 8081

spring:
  application:
    name: account-service
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

mybatis-plus:
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true  # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    call-setters-on-nulls: true # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
  mapper-locations: classpath:/mapper/*.xml